apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitops-rolebinding
subjects:
- kind: ServiceAccount
  name: gitops-serviceaccount
  namespace: default
roleRef:
  kind: Role
  name: gitops-role
  apiGroup: rbac.authorization.k8s.io